spring:
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      url: jdbc:h2:file:~/h2db
      username: sa
      password: null
      driver-class-name: org.h2.Driver
      platform: h2 # para rodar script data-h2.sql
   jpa:
      hibernate:
         ddl-auto: update